SSoc-Client/package-lock.json, SSoc-Client/package.json
**개요**
- #2 
- React Native Expo 프로젝트 세팅 진행
**타입**
**작업 사항**
1. 의존성 추가
"react-native-safe-area-context": "^4.7.2",
"react-native-screens": "^3.25.0"
"@react-navigation/native": "^6.1.7",
"@react-navigation/native-stack": "^6.9.13",
2. 의존성 충돌 해결  
react-native-safe-area-context@4.7.2 - expected version: 4.6.3
react-native-screens@3.25.0 - expected version: ~3.22.0
종속 버전에 맞게 종속성 새로 설치 진행 
3. iOS 정상 렌더링 확인 (Xcode emulator : iPhone14 (iOS 16.2)
=> feat: react native expo 종속성 설치 (#2)

Backend/src/main/java/gwangju/ssafy/backend/component/shinhan/ShinhanApiFeignClient.java, Backend/src/main/java/gwangju/ssafy/backend/component/shinhan/ShinhanApiKey.java, Backend/src/main/java/gwangju/ssafy/backend/component/shinhan/ShinhanBankService.java, Backend/src/main/java/gwangju/ssafy/backend/component/shinhan/ShinhanBankServiceImpl.java, Backend/src/main/java/gwangju/ssafy/backend/component/shinhan/dto/BalanceDetail.java, Backend/src/main/java/gwangju/ssafy/backend/component/shinhan/dto/ShinhanApiDto.java, Backend/src/main/java/gwangju/ssafy/backend/component/shinhan/dto/ShinhanBalanceDetailApi.java, Backend/src/main/java/gwangju/ssafy/backend/component/shinhan/dto/ShinhanResponseHeader.java, Backend/src/main/java/gwangju/ssafy/backend/config/HeaderConfiguration.java, Backend/src/main/java/gwangju/ssafy/backend/config/OpenFeignConfig.java
**개요**
- #6 
- 신한 계좌 잔액 조회 기능 구현
**타입**
**작업 사항**
- OpenFeign을 이용하여 신한은행 API와 연동하였습니다.
- 계좌 번호를 입력하면 계좌 내역을 조회할 수 있는 기능을 구현하였습니다.
=> feat: 신한 계좌 잔액 조회 기능 구현

Backend/src/main/java/gwangju/ssafy/backend/component/shinhan/ShinhanApiFeignClient.java, Backend/src/main/java/gwangju/ssafy/backend/component/shinhan/ShinhanBankService.java, Backend/src/main/java/gwangju/ssafy/backend/component/shinhan/ShinhanBankServiceImpl.java, Backend/src/main/java/gwangju/ssafy/backend/component/shinhan/dto/ShinhanTansactionApi.java, Backend/src/main/java/gwangju/ssafy/backend/component/shinhan/dto/TransactionInfo.java
**개요**
- #6 
- 신한 거래 내역 조회 기능 구현
**타입**
**작업 사항**
- OpenFeign을 이용하여 신한은행 API와 연동하였습니다.
- 계좌 번호를 입력하면 거래 내역을 조회할 수 있는 기능을 구현하였습니다.
* FeignClient로 받아온 데이터
* 변환 데이터
=> feat: 신한 거래 내역 조회 기능 구현

Backend/src/main/java/gwangju/ssafy/backend/component/shinhan/ShinhanApiFeignClient.java, Backend/src/main/java/gwangju/ssafy/backend/component/shinhan/ShinhanBankServiceImpl.java, Backend/src/main/java/gwangju/ssafy/backend/component/shinhan/dto/ShinhanTransactionApi.java
**개요**
- #6 
- ShinhanTransactionApi 오탈자 수정
**타입**
**작업 사항**
- ShinhanTansactionApi  -> ShinhanTransactionApi로 오탈자 수정하였습니다.
=> chore: ShinhanTransactionApi 오탈자 수정

Backend/src/main/java/gwangju/ssafy/backend/component/shinhan/ShinhanApiFeignClient.java, Backend/src/main/java/gwangju/ssafy/backend/component/shinhan/ShinhanBankService.java, Backend/src/main/java/gwangju/ssafy/backend/component/shinhan/ShinhanBankServiceImpl.java, Backend/src/main/java/gwangju/ssafy/backend/component/shinhan/dto/ShinhanTransferApi.java, Backend/src/main/java/gwangju/ssafy/backend/component/shinhan/dto/TransferRequest.java, Backend/src/main/java/gwangju/ssafy/backend/component/shinhan/dto/TransferResult.java
**개요**
- #6 
- 신한 이체 기능 구현
**타입**
**작업 사항**
- 출금 계좌번호 , 입금 은행 코드, 입금 계좌번호, 이체 금액, 출금 메세지, 입금 메세지를 입력하여 신한 API를 통해 이체를 하는 기능을 구현하였습니다. 
**Others**
=> feat: 신한 이체 기능 구현

Backend/src/main/java/gwangju/ssafy/backend/group/entity/Group.java, Backend/src/main/java/gwangju/ssafy/backend/group/entity/School.java, Backend/src/main/java/gwangju/ssafy/backend/group/entity/SchoolEmail.java
**개요**
- #14 
- 그룹 및 학교, 학교이메일 엔티티 작성
**타입**
**작업 사항**
- erd를 기반으로 그룹 관련 기초 엔티티를 작성하였습니다.
- 생성날짜, 수정날짜 컬럼은 추후에 JPA Audit으로 리팩토링하여 추가할 예정입니다.
=> feat: 그룹 및 학교, 학교이메일 엔티티 작성

SSoc-Client/package-lock.json, SSoc-Client/package.json
**개요**
- #4 
- React Native 의존성 추가
**타입**
**작업 사항**
1. 의존성 추가
"react-native-responsive-screen": "^1.4.2",
"@react-native-async-storage/async-storage": "^1.19.3",
"@react-navigation/bottom-tabs": "^6.5.8",
=> feat: react native expo 종속성 추가 설치

SSoc-Client/App.js, SSoc-Client/src/modules/Card.js, SSoc-Client/src/modules/MainSerachBar.js, SSoc-Client/src/screens/MainScreen.js
---
**개요**
- #21 Closes
- 메인 스크린 개발 
**타입**
**작업 사항**
- 카드 컴포넌트 개발 
- horizontal scroll view 구현 
- 메인 검색창 개발 
- 메인 스크린 개발 
=> feat: mainscreen 개발 

SSoc-Client/App.js, SSoc-Client/src/RootApp.js, SSoc-Client/src/SplashView.js
**개요**
- #23 Closes 
- Splash View를 제작하였습니다. 
**타입**
**작업 사항**
- Splash View 개발 
- 기본적인 로그인 관련 혹을 작성하였습니다.
- 서버에서 로그인 인증 인가 개발전이기 때문에 목 로직을 적용하여 2초간 Splash View가 렌더링 되도록 하였습니다. 
2초간 렌더링 후 메인페이지로 이동합니다.
=> feat: Splash View 개발 (#23)

SSoc-Client/App.js, SSoc-Client/src/RootApp.js, SSoc-Client/src/modules/MainHeader.js, SSoc-Client/src/modules/StackHeader.js, SSoc-Client/src/navigations/MainNavigations/MainBottomTabNavigation.js, SSoc-Client/src/navigations/MainNavigations/RootStackNavigation.js, SSoc-Client/src/screens/MainBottomTabs/MainScreen.js, SSoc-Client/src/screens/MainBottomTabs/SearchResultScreen.js, SSoc-Client/src/screens/MainBottomTabs/SettingScreen.js, SSoc-Client/src/screens/StackDetailScreen.js
---
**개요**
- #25 Closes
- Main Bottom Tab 개발 
**타입**
**작업 사항**
- main bottom tab에 사용할 screen구현
- Main bottom tab 구현
- Main Bottom tab에서 사용할 스택 네비게이션 구현
- Main Header 세팅화면 바로가기 구현
- StackHeader 뒤로가기 및 세팅화면 바로가기 구현
- App.js에 네비게이션 적용]
=> feat: Main Bottom Tab(#25) 

Backend/src/main/java/gwangju/ssafy/backend/admin/controller/AdminGroupController.java, Backend/src/main/java/gwangju/ssafy/backend/common/dto/Message.java, Backend/src/main/java/gwangju/ssafy/backend/group/dto/CreateGroupRequest.java, Backend/src/main/java/gwangju/ssafy/backend/group/entity/Group.java, Backend/src/main/java/gwangju/ssafy/backend/group/entity/GroupMember.java, Backend/src/main/java/gwangju/ssafy/backend/group/entity/enums/GroupMemberRole.java, Backend/src/main/java/gwangju/ssafy/backend/group/repository/GroupMemberRepository.java, Backend/src/main/java/gwangju/ssafy/backend/group/repository/GroupRepository.java, Backend/src/main/java/gwangju/ssafy/backend/group/repository/SchoolRepository.java, Backend/src/main/java/gwangju/ssafy/backend/group/service/GroupMemberService.java, Backend/src/main/java/gwangju/ssafy/backend/group/service/GroupService.java, Backend/src/main/java/gwangju/ssafy/backend/group/service/impl/GroupMemberServiceImpl.java, Backend/src/main/java/gwangju/ssafy/backend/group/service/impl/GroupServiceImpl.java
**개요**
- #28 
- 그룹 생성 API 구현
**타입**
**작업 사항**
- 그룹 생성 API를 구현하였습니다.
- 그룹 생성 시, 관리자 그룹원도 함께 추가되어 저장됩니다.
=> feat: 그룹 생성 API 구현

Backend/src/main/java/gwangju/ssafy/backend/email/EmailService.java, Backend/src/main/java/gwangju/ssafy/backend/email/EmailServiceImpl.java, Backend/src/main/java/gwangju/ssafy/backend/user/controller/UserController.java, Backend/src/main/java/gwangju/ssafy/backend/user/controller/UserRestController.java, Backend/src/main/java/gwangju/ssafy/backend/user/repository/UserRepository.java, Backend/src/main/java/gwangju/ssafy/backend/user/service/UserService.java, Backend/src/main/java/gwangju/ssafy/backend/user/service/UserServiceImpl.java
**개요**
- #18 
- 이메일 인증 코드 기능 개발
- EmailService 생성
- EmailServiceImpl 생성
**타입**
**작업 사항**
- Email 서비스와 관련된 intertface 및 java 파일을 생성하여 기능 구현을 하였습니다.
- 해당 이메일 인증코드를 통해 Controller에서 return한 인증코드를 통해 비교해서 값이 같은 경우 회원가입 처리가 완료되게끔 처리하였습니다.
**Test**🧪
- 이메일 인증코드가 제대로 발송되는지 테스트 하였습니다.
1. RequestParam형태 (key - value) 형식으로 데이터 보내줌
2. 서버내에서 제대로 발송 처리 완료
3. 이메일 인증코드 제대로 왔는지 확인
=> feat: 회원가입시 필요한 이메일 인증코드 기능 구현 

Backend/build.gradle, Backend/src/main/java/gwangju/ssafy/backend/BackendApplication.java, Backend/src/main/java/gwangju/ssafy/backend/config/SecurityConfig.java, Backend/src/main/java/gwangju/ssafy/backend/domain/user/controller/UserController.java, Backend/src/main/java/gwangju/ssafy/backend/domain/user/controller/UserRestController.java, Backend/src/main/java/gwangju/ssafy/backend/domain/user/entity/User.java, Backend/src/main/java/gwangju/ssafy/backend/domain/user/entity/enums/UserRole.java, Backend/src/main/java/gwangju/ssafy/backend/domain/user/repository/UserRepository.java, Backend/src/main/java/gwangju/ssafy/backend/domain/user/service/UserService.java, Backend/src/main/java/gwangju/ssafy/backend/domain/user/service/UserServiceImpl.java, Backend/src/main/java/gwangju/ssafy/backend/global/config/SecurityConfig.java, Backend/src/main/java/gwangju/ssafy/backend/global/infra/email/EmailServiceImpl.java, Backend/src/test/java/gwangju/ssafy/backend/user/repository/UserRepositoryTest.java, Backend/src/test/java/gwangju/ssafy/backend/user/service/UserServiceTest.java
**개요**
- #31 
- Spring Security 연동
- 회원가입 시 유저 패스워드 암호화 처리
- 커스텀 로그인 처리
**타입**
**작업 사항**
- Spring Secuirty를 연동하기 위해 build.gradle파일에 Security 추가 및 Spring security config 파일 생성 및 securityFilterChain 이용, 해당 Security 설정 커스텀화 하였습니다.
- PasswordEncoder를 사용하여 회원가입시 DB에 저장되는 패스워드 값을 암호화 처리하였습니다.
- Spring Security를 이용하여 커스텀 로그인 처리를 하였습니다. (유저 이메일, 유저 패스워드를 비교하여 같으면 true)
**Test**🧪
- 회원가입 시 DB에 저장되는 패스워드 값이 암호화 되는지 테스트 하였습니다.
- 커스텀 로그인 처리가 제대로 되는지 확인하였습니다.
1. JSON 형식으로 회원가입 시 필요한 데이터 보내줌
2. 회원정보 입력받은 값 DB에 저장 및 유저 패스워드 암호화 됐는지 확인
3. DB에 저장된 회원 아이디 및 비밀번호를 입력해서 제대로 로그인 되는지 확인
4. 틀린 비밀번호를 입력할 시 로그인 처리가 안되는지 확인
5. DB에 저장되지 않은 이메일을 입력할 시 에러를 던져줌
=> feat: Srping Security 연동 및 로그인 처리 및 패스워드 암호화 기능 구현

Backend/src/main/java/gwangju/ssafy/backend/domain/transaction/controller/GroupAccountController.java, Backend/src/main/java/gwangju/ssafy/backend/domain/transaction/dto/UnregisterGroupAccountRequest.java, Backend/src/main/java/gwangju/ssafy/backend/domain/transaction/entity/GroupAccount.java, Backend/src/main/java/gwangju/ssafy/backend/domain/transaction/repository/GroupAccountRepository.java, Backend/src/main/java/gwangju/ssafy/backend/domain/transaction/service/GroupAccountService.java, Backend/src/main/java/gwangju/ssafy/backend/domain/transaction/service/impl/GroupAccountServiceImpl.java, Backend/src/main/java/gwangju/ssafy/backend/global/infra/batch/jobs/DailyTransactionReader.java
**개요**
- #16 
- 그룹 계좌 해제 API 구현
**타입**
**작업 사항**
- 그룹 매니저가 계좌 해제 요청 시, 계좌 비활성화 처리를 합니다.
=> feat: 그룹 계좌 해제 API 구현

SSoc-Client/src/modules/ImgEditButton.js, SSoc-Client/src/modules/SettingProfileImage.js
**개요**
- #51 
- 이미지 업로드 기능 추가
**타입**
**작업 사항**
- SettingProfileImage.js 기능 추가
=> feat: 이미지 업로드 기능 구현

Backend/src/main/java/gwangju/ssafy/backend/domain/group/dto/EditGroupInfoRequest.java, Backend/src/main/java/gwangju/ssafy/backend/domain/group/entity/Group.java, Backend/src/main/java/gwangju/ssafy/backend/domain/group/service/impl/GroupServiceImpl.java
**개요**
- #28 
- 그룹 썸네일 변경 기능 추가
**타입**
**작업 사항**
- 그룹 썸네일이 빠져있어서 추가하고, 그에 따른 수정 기능도 추가하였습니다.
=> feat: 그룹 썸네일 변경 기능 추가

Backend/build.gradle, Backend/src/main/java/gwangju/ssafy/backend/domain/user/controller/UserRestController.java, Backend/src/main/java/gwangju/ssafy/backend/domain/user/dto/LoginUserDto.java, Backend/src/main/java/gwangju/ssafy/backend/domain/user/dto/UserRequestDto.java, Backend/src/main/java/gwangju/ssafy/backend/domain/user/entity/User.java, Backend/src/main/java/gwangju/ssafy/backend/domain/user/repository/UserRepository.java, Backend/src/main/java/gwangju/ssafy/backend/domain/user/service/CustomUserDetailsService.java, Backend/src/main/java/gwangju/ssafy/backend/domain/user/service/UserService.java, Backend/src/main/java/gwangju/ssafy/backend/domain/user/service/UserServiceImpl.java, Backend/src/main/java/gwangju/ssafy/backend/global/common/dto/TokenDto.java, Backend/src/main/java/gwangju/ssafy/backend/global/common/dto/TokenRequestDto.java, Backend/src/main/java/gwangju/ssafy/backend/global/component/jwt/JwtAccessDeniedHandler.java, Backend/src/main/java/gwangju/ssafy/backend/global/component/jwt/JwtAuthenticationEntryPoint.java, Backend/src/main/java/gwangju/ssafy/backend/global/component/jwt/JwtFilter.java, Backend/src/main/java/gwangju/ssafy/backend/global/component/jwt/TokenProvider.java, Backend/src/main/java/gwangju/ssafy/backend/global/component/util/SecurityUtil.java, Backend/src/main/java/gwangju/ssafy/backend/global/config/JwtSecurityConfig.java, Backend/src/main/java/gwangju/ssafy/backend/global/config/SecurityConfig.java
**개요**
- #31 
- Spring Security와 함께 JWT를 연동하였습니다.
- 유저 로그인 시 JWT 토큰을 발급하도록 설정하였습니다.
- JWT 토큰을 재발급하는 기능을 구현하였습니다.
- JWT 토큰 안에 accessToken값과 refreshToken값을 담도록 구현하였습니다.
**타입**
**작업 사항**
- Spring boot에서 Spring Security와 더불어 JWT 설정을 완료하였습니다.
- 유저가 로그인 시 JWT 토큰을 발급하도록 기능을 구현하였습니다.
- 추후에 로그인 시 JWT 토큰값만 넘기는 것 뿐만 아니라 로그인한 유저의 회원정보도 같이 넘길 예정입니다.
=> feat: Srping Security 및 JWT 연동, JWT를 활용한 로그인 기능 구현

Backend/src/main/java/gwangju/ssafy/backend/domain/group/controller/GroupMemberController.java, Backend/src/main/java/gwangju/ssafy/backend/domain/group/dto/GetMemberRoleRequest.java, Backend/src/main/java/gwangju/ssafy/backend/domain/group/dto/GetMemberRoleResponse.java, Backend/src/main/java/gwangju/ssafy/backend/domain/group/service/GroupMemberService.java, Backend/src/main/java/gwangju/ssafy/backend/domain/group/service/impl/GroupMemberServiceImpl.java, Backend/src/main/java/gwangju/ssafy/backend/domain/transaction/controller/GroupAccountController.java
**개요**
- #56 
- 그룹원 권한 조회 API 구현
**타입**
**작업 사항**
- 해당 그룹에 관한 유저의 권한을 조회하는 API를 구현했습니다.
=> feat: 그룹원 권한 조회 API 구현

SSoc-Client/package.json
**개요**
- json 파일 중 , 생략 오류 수정
**타입**
**작업 사항**
- package.json
=> fix: 의존성 comflict 해결 중 , 생략부 오류 수정

Backend/src/main/java/gwangju/ssafy/backend/domain/group/controller/GroupController.java, Backend/src/main/java/gwangju/ssafy/backend/domain/group/dto/GetGroupInfoDetailRequest.java, Backend/src/main/java/gwangju/ssafy/backend/domain/group/dto/GroupDetailInfo.java, Backend/src/main/java/gwangju/ssafy/backend/domain/group/repository/GroupMemberRepository.java, Backend/src/main/java/gwangju/ssafy/backend/domain/group/service/GroupService.java, Backend/src/main/java/gwangju/ssafy/backend/domain/group/service/impl/GroupServiceImpl.java
**개요**
- #28
- 그룹 상세 조회 API 구현
**타입**
**작업 사항**
- 그룹 상세 조회 API를 구현했습니다.
=> feat: 그룹 상세 조회 API 구현

SSoc-Client/src/SplashView.js, SSoc-Client/src/modules/AuthModules/AuthStackHeader.js, SSoc-Client/src/modules/AuthModules/SchoolEmailInput.js, SSoc-Client/src/modules/AuthModules/UserInfoInput.js, SSoc-Client/src/navigations/AuthNavigations/AuthStackNavigation.js, SSoc-Client/src/screens/AuthScreen/FindPassWordScreen.js, SSoc-Client/src/screens/AuthScreen/LoginScreen.js, SSoc-Client/src/screens/AuthScreen/RegisterScreen.js, SSoc-Client/src/screens/AuthScreen/SchoolEmailScreen.js, SSoc-Client/src/util/AsyncUtil.js, SSoc-Client/src/util/FetchUtil.js
**개요**
- 서버와 비동기 통신을 위한 준비 완료
- API 서버가 현재 완료되지 않아 fetch로 비동기 시 더미데이터로 임시 삽입 후 처리
**타입**
**작업 사항**
- AuthScreen 선작업 완료
=> feat: AuthScreen 비동기 처리 완료

SSoc-Client/src/modules/EditInputShow.js, SSoc-Client/src/modules/SettingInfoInput.js, SSoc-Client/src/modules/SettingUserInfo.js
**개요**
- 서버와 비동기 통신을 위한 준비 완료
- API 서버가 현재 완료되지 않아 fetch로 비동기 시 더미데이터로 임시 삽입 후 처리
**타입**
**작업 사항**
- SettingScreen 내 회원정보 변경 선작업 완료
=> feat: 회원정보 수정 중 이미지 수정 제외 api 더미데이터로 선작업 완료

Backend/src/main/java/gwangju/ssafy/backend/domain/transaction/controller/TransactionStatisticsController.java, Backend/src/main/java/gwangju/ssafy/backend/domain/transaction/dto/DailyStatisticsInfo.java, Backend/src/main/java/gwangju/ssafy/backend/domain/transaction/dto/MonthlyStatisticsInfo.java, Backend/src/main/java/gwangju/ssafy/backend/domain/transaction/dto/SearchDailyStatisticsRequest.java, Backend/src/main/java/gwangju/ssafy/backend/domain/transaction/dto/SearchMonthlyStatisticsRequest.java, Backend/src/main/java/gwangju/ssafy/backend/domain/transaction/repository/DailyTransactionStatisticsRepository.java, Backend/src/main/java/gwangju/ssafy/backend/domain/transaction/repository/MonthlyTransactionStatisticsRepository.java, Backend/src/main/java/gwangju/ssafy/backend/domain/transaction/service/TransactionStatisticsService.java, Backend/src/main/java/gwangju/ssafy/backend/domain/transaction/service/impl/TransactionStatisticsServiceImpl.java
**개요**
- #74 
-그룹계좌 거래내역 월간 통계 조회 API 구현
**타입**
**작업 사항**
- 원하는 년도로 월간 통계를 조회할 수 있는 API를 구현했습니다.
=> feat: 그룹계좌 거래내역 월간 통계 조회 API 구현

Backend/src/main/java/gwangju/ssafy/backend/domain/board/controller/PostController.java, Backend/src/main/java/gwangju/ssafy/backend/domain/board/dto/CreatePostRequest.java, Backend/src/main/java/gwangju/ssafy/backend/domain/board/dto/DeletePostRequest.java, Backend/src/main/java/gwangju/ssafy/backend/domain/board/dto/EditPostRequest.java, Backend/src/main/java/gwangju/ssafy/backend/domain/board/dto/PostInfo.java, Backend/src/main/java/gwangju/ssafy/backend/domain/board/dto/SearchPostRequest.java, Backend/src/main/java/gwangju/ssafy/backend/domain/board/dto/cond/SearchPostCond.java, Backend/src/main/java/gwangju/ssafy/backend/domain/board/entity/Post.java, Backend/src/main/java/gwangju/ssafy/backend/domain/board/entity/enums/PostCategory.java, Backend/src/main/java/gwangju/ssafy/backend/domain/board/repository/PostRepository.java, Backend/src/main/java/gwangju/ssafy/backend/domain/board/repository/QuerydslPostRepository.java, Backend/src/main/java/gwangju/ssafy/backend/domain/board/repository/impl/QuerydslPostRepositoryImpl.java, Backend/src/main/java/gwangju/ssafy/backend/domain/board/service/PostService.java, Backend/src/main/java/gwangju/ssafy/backend/domain/board/service/impl/PostServiceImpl.java
**개요**
- #94
- 게시글 CRUD API 구현
**타입**
**작업 사항**
- 게시글 CRUD API 구현를 구현했습니다.
=> feat: 게시글 CRUD API 구현

SSoc-Client/src/modules/Board/AnswerCommentCard.js, SSoc-Client/src/modules/Board/AnswerCommentModal.js, SSoc-Client/src/modules/Board/CommentCard.js, SSoc-Client/src/modules/Board/CommentModal.js, SSoc-Client/src/modules/Board/ContentCard.js, SSoc-Client/src/modules/Board/ContentDetailFooter.js, SSoc-Client/src/modules/Board/ContentDetailPost.js, SSoc-Client/src/modules/Board/ContentDetailTitle.js, SSoc-Client/src/modules/Board/ContentList.js, SSoc-Client/src/modules/Board/WriteContentForm.js, SSoc-Client/src/screens/GroupDetailBottomTabs/Board/BoardContentScreen.js, SSoc-Client/src/screens/GroupDetailBottomTabs/Board/BoardDetatilTopTabs.js
**개요**
**타입**
**작업 사항**
- boardScreen관련 모든 작업
=> feat: 게시판 UI 구현 완료

Backend/src/main/java/gwangju/ssafy/backend/domain/user/controller/UserRestController.java, Backend/src/main/java/gwangju/ssafy/backend/global/component/jwt/JwtParser.java, Backend/src/main/java/gwangju/ssafy/backend/global/component/jwt/dto/TokenUserInfoDto.java, Backend/src/main/java/gwangju/ssafy/backend/global/component/jwt/security/JwtAuthenticationFilter.java, Backend/src/main/java/gwangju/ssafy/backend/global/exception/ExceptionHandlerFilter.java
- #105 
- 프론트 앞단쪽에 보내주는 AccessToken과 RefreshToken에 ""(쌍따옴표)가 붙여서 나오는 경우를 처리해줬습니다. 
**타입**
정상 실행 확인 하였습니다.
=> fix: AccessToken, RefreshToken 버그 예외 관련 처리 

Backend/src/main/java/gwangju/ssafy/backend/domain/schedule/controller/ScheduleController.java, Backend/src/main/java/gwangju/ssafy/backend/domain/schedule/exception/ScheduleError.java, Backend/src/main/java/gwangju/ssafy/backend/domain/schedule/exception/ScheduleException.java, Backend/src/main/java/gwangju/ssafy/backend/domain/schedule/exception/ScheduleExceptionHandler.java, Backend/src/main/java/gwangju/ssafy/backend/domain/schedule/service/impl/ScheduleServiceImpl.java
**개요**
- #105 
- 스케줄 도메인 예외 처리 및 시큐리티 적용
**타입**
**작업 사항**
-  시큐리티 권한 체크
-  에러 핸들링
=> feat: 스케줄 도메인 예외 처리 및 시큐리티 적용

Backend/src/main/java/gwangju/ssafy/backend/domain/group/controller/GroupSignupController.java, Backend/src/main/java/gwangju/ssafy/backend/domain/group/dto/GroupSignupInfo.java, Backend/src/main/java/gwangju/ssafy/backend/domain/group/service/impl/GroupSignupServiceImpl.java
**개요**
- #119 
- 그룹 가입 신청 관련 API Security 적용
- 해당 API 관련 Exception 핸들링 적용
**타입**
**작업 사항**
- Security 적용이 완료됨에 따라 그룹 가입 신청 관련 API들을 Security 적용하였습니다.  또한 해당 API들의 Exception 핸들링을 적용하였습니다.
=> feat: 그룹 가입 신청 관련 API Security 적용 및 Exception 핸들링 적용

SSoc-Client/src/navigations/GroupDetailNavigations/GroupDetailStackNavigation.js, SSoc-Client/src/screens/GroupDetailBottomTabs/Manage/MemberManage/MemberManageScreen.js, SSoc-Client/src/screens/GroupDetailBottomTabs/Manage/MemberManage/MemberManageTopTabs.js, SSoc-Client/src/screens/GroupDetailBottomTabs/Manage/MemberManage/RequestManageScreen.js
**개요**
- #116 
**타입**
**작업 사항**
-  그룹원 및 가입 신청 관리 페이지
=> feat: [Client] 그룹원 및 가입 신청 관리 페이지(#116)

SSoc-Client/src/navigations/GroupDetailNavigations/GroupDetailStackNavigation.js
**개요**
- GroupDetailStackNavigation내 스크린 중복 Merge로 인한 에러 수정
**타입**
=> fix: GroupDetailStackNavigation내 스크린 중복 Merge로 인한 에러 수정

Backend/src/main/java/gwangju/ssafy/backend/domain/group/controller/GroupMemberController.java, Backend/src/main/java/gwangju/ssafy/backend/domain/group/dto/GetGroupMemberInfo.java, Backend/src/main/java/gwangju/ssafy/backend/domain/group/repository/GroupMemberRepository.java, Backend/src/main/java/gwangju/ssafy/backend/domain/group/repository/GroupSignupRepository.java, Backend/src/main/java/gwangju/ssafy/backend/domain/group/service/GroupMemberService.java, Backend/src/main/java/gwangju/ssafy/backend/domain/group/service/impl/GroupMemberServiceImpl.java
**개요**
- #122 
- 그룹멤버(소속원)을 조회하는 기능 구현
**타입**
**작업 사항**
- 해당 그룹멤버(소속원)을 조회하는 기능 구현 (해당 로그인한 그룹 관리자는 조회목록에서 제외되게끔) 
=> feat: 해당 그룹 멤버 전체 조회

Backend/src/main/java/gwangju/ssafy/backend/domain/group/controller/GroupMemberController.java, Backend/src/main/java/gwangju/ssafy/backend/domain/group/controller/GroupSignupController.java, Backend/src/main/java/gwangju/ssafy/backend/domain/group/dto/DeleteGroupMemberInfo.java, Backend/src/main/java/gwangju/ssafy/backend/domain/group/repository/GroupMemberRepository.java, Backend/src/main/java/gwangju/ssafy/backend/domain/group/repository/GroupSignupRepository.java, Backend/src/main/java/gwangju/ssafy/backend/domain/group/service/GroupMemberService.java, Backend/src/main/java/gwangju/ssafy/backend/domain/group/service/GroupSignupService.java, Backend/src/main/java/gwangju/ssafy/backend/domain/group/service/impl/GroupMemberServiceImpl.java, Backend/src/main/java/gwangju/ssafy/backend/domain/group/service/impl/GroupSignupServiceImpl.java
**개요**
- #122 
- 그룹장이 해당 그룹원 삭제하는 기능 구현
**타입**
**작업 사항**
- 그룹장이 해당 그룹원 삭제하는 기능 구현 (해당 그룹 아이디와 유저 아이디를 이용) 
=> feat: 그룹장이 해당 그룹원 삭제하는 기능 구현

Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/controller/ProductController.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/dto/ProductSimpleInfo.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/entity/Product.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/entity/enums/ProductCategory.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/repository/ProductRepository.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/service/ProductService.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/service/impl/ProductServiceImpl.java, Backend/src/main/java/gwangju/ssafy/backend/global/component/jwt/JwtParser.java, Backend/src/main/java/gwangju/ssafy/backend/global/component/jwt/security/JwtAuthenticationEntryPoint.java
**개요**
- #131 
- 로그인한 회원이면서 해당그룹에 가입되어 있는 유저가 대여 물품 (예약 물품) 조회하는 기능 구현
**타입**
**작업 사항**
- 해당 그룹의 대여 물품 (예약 물품) 조회하는 기능을 구현 (로그인한 유저가 가입된 해당 그룹 아이디를 이용)
=> feat: 해당 그룹의 대여 물품 (예약 물품) 조회 기능 구현

SSoc-Client/src/modules/Board/AnswerCommentModal.js, SSoc-Client/src/modules/Board/CommentCard.js, SSoc-Client/src/modules/Board/CommentModal.js, SSoc-Client/src/modules/Board/ContentCard.js, SSoc-Client/src/modules/Board/ContentDetailFooter.js, SSoc-Client/src/modules/Board/ContentDetailTitle.js, SSoc-Client/src/modules/Board/ContentList.js, SSoc-Client/src/modules/Board/DetailContentStackHeader.js, SSoc-Client/src/modules/Board/EditComment.js, SSoc-Client/src/modules/Board/EditContent.js, SSoc-Client/src/modules/Board/WriteContentForm.js, SSoc-Client/src/modules/Card.js, SSoc-Client/src/navigations/GroupDetailNavigations/GroupDetailBottomTabNavigation.js, SSoc-Client/src/screens/GroupDetailBottomTabs/Board/BoardContentList.js, SSoc-Client/src/screens/GroupDetailBottomTabs/Board/BoardDetailScreen.js, SSoc-Client/src/screens/GroupDetailBottomTabs/Board/BoardDetatilTopTabs.js, SSoc-Client/src/screens/GroupDetailBottomTabs/Board/ContentDetailScreen.js, SSoc-Client/src/screens/MainBottomTabs/MainScreen.js, SSoc-Client/src/util/FetchUtil.js
**개요**
- Board 댓글 영역까지 fetch 완료
**타입**
=> feat: Board 댓글 영역까지 fetch 완료

Backend/src/main/java/gwangju/ssafy/backend/global/exception/ErrorCode.java
**개요**
- jwt 토큰 관련 ErrorCode 포함을 안시켜서 해당 에러 발생 핫픽스
**타입**
=> hotfix: jwt 토큰 관련 ErrorCode 포함해서 다시 올림

Backend/src/main/java/gwangju/ssafy/backend/domain/account/controller/TransactionController.java, Backend/src/main/java/gwangju/ssafy/backend/domain/account/dto/TransactionInfo.java, Backend/src/main/java/gwangju/ssafy/backend/domain/account/repository/QueryDslTransactionRepository.java, Backend/src/main/java/gwangju/ssafy/backend/domain/account/repository/TransactionRepository.java, Backend/src/main/java/gwangju/ssafy/backend/domain/account/repository/impl/QueryDslTransactionRepositoryImpl.java, Backend/src/main/java/gwangju/ssafy/backend/domain/account/service/TransactionService.java, Backend/src/main/java/gwangju/ssafy/backend/domain/account/service/impl/TransactionServiceImpl.java, Backend/src/main/java/gwangju/ssafy/backend/global/component/excel/ExcelColumn.java, Backend/src/main/java/gwangju/ssafy/backend/global/component/excel/ExcelColumnExtractor.java, Backend/src/main/java/gwangju/ssafy/backend/global/component/excel/SimpleExcelFile.java, Backend/src/main/java/gwangju/ssafy/backend/global/exception/ExcelException.java, Backend/src/main/java/gwangju/ssafy/backend/global/exception/GlobalException.java
**개요**
- #124 
- 거래내역 엑셀 다운로드 기능 구현
**타입**
**작업 사항**
-  POI를 이용해서 거래내역 엑셀 다운로드 구현
=> feat: 거래내역 엑셀 다운로드 기능 구현

SSoc-Client/src/modules/Board/AnswerCommentCard.js, SSoc-Client/src/modules/Board/AnswerCommentModal.js, SSoc-Client/src/modules/Board/CommentCard.js, SSoc-Client/src/modules/Board/CommentModal.js, SSoc-Client/src/modules/Board/ContentDetailTitle.js, SSoc-Client/src/modules/Board/EditReply.js, SSoc-Client/src/modules/SettingDeleteUser.js, SSoc-Client/src/modules/SettingLogout.js, SSoc-Client/src/util/FetchUtil.js
**개요**
- Board 비동기 통신 완료 및 api 내에서 일어나는 오류 사항 발견 및 수정
**타입**
=> feat: Board 비동기 통신 완료

SSoc-Client/src/modules/AuthModules/SchoolEmailInput.js, SSoc-Client/src/modules/AuthModules/UserInfoInput.js, SSoc-Client/src/modules/Board/EditContent.js, SSoc-Client/src/modules/EditInputShow.js, SSoc-Client/src/modules/SettingInfoInput.js, SSoc-Client/src/modules/SettingLogout.js, SSoc-Client/src/screens/AuthScreen/RegisterSuccessScreen.js, SSoc-Client/src/screens/AuthScreen/SchoolEmailScreen.js, SSoc-Client/src/util/FetchUtil.js
**개요**
- Board 게시글 수정 시 category 없음 현상 해결
- 회원정보 수정 비동기 통신 완료(이미지 제외)
- 메일인증 시 api에서 오래 머무는 현상 완화를 위한 loader 삽입
- 불필요 console.log 제거
**타입**
=> feat: 회원정보 수정 비동기 통신 완료 및 디테일 고도화

Backend/src/main/java/gwangju/ssafy/backend/domain/group/service/impl/GroupMemberServiceImpl.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/controller/ProductController.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/controller/ReservationController.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/dto/ReservationSimpleInfo.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/entity/Reservation.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/repository/ReservationRepository.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/service/ReservationService.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/service/impl/ReservationServiceImpl.java
**개요**
- #140 
- 예약 상세 페이지에서 날짜 선택 시 해당 그룹의 대여 물품 예약 가능 여부 상세 조회 기능을 구현
**타입**
**작업 사항**
- 예약 상세 페이지에서 날짜 선택 시 해당 그룹의 대여 물품 예약 가능 여부를 시간대별로 확인할 수 있는 상세 조회 기능 API를 구현하였습니다.
=> feat: 날짜 선택 시 해당 그룹의 대여 물품 예약 가능 여부 상세 조회 기능 구현 (그룹에 가입되어 있는 유저 입장) 

Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/controller/ReservationController.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/service/ReservationService.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/service/impl/ReservationServiceImpl.java
**개요**
- #140 
- 해당 그룹의 대여 물품(예약 물품) 예약하기 기능을 구현 (그룹에 가입되어 있는 유저 입장)
**타입**
**작업 사항**
- 해당 그룹의 대여 물품(예약 물품)을 예약하는 기능을 구현하였습니다.
=> feat: 해당 그룹의 대여 물품(예약 물품) 예약하기 기능 구현

Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/controller/ReservationController.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/dto/GetReservationUser.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/repository/ReservationRepository.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/service/ReservationService.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/service/impl/ReservationServiceImpl.java
**개요**
- #140 
- 해당 그룹의 그룹 관리자가 예약 내역을 조회하는 기능 구현
**타입**
**작업 사항**
- 해당 그룹의 그룹 관리자가 예약 내역 전체를 조회하는 기능을 구현하였습니다.
- 해당 그룹의 그룹 관리자가 예약 내역 반납 여부에 따른 조회하는 기능을 구현하였습니다.
- 해당 그룹의 그룹 관리자가 예약 내역 승인 여부에 따른 조회하는 기능을 구현하였습니다.
=> feat: 그룹 관리자가 예약 내역 조회하는 기능 구현

Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/controller/ReservationController.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/entity/Reservation.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/repository/ReservationRepository.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/service/ReservationService.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/service/impl/ReservationServiceImpl.java
**개요**
- #140 
- 해당 그룹의 그룹 관리자가 예약 내역을 선택하여 해당 예약 승인 OR 거절 처리하는 기능 구현
**타입**
**작업 사항**
- 해당 그룹의 예약 내역을 선택하여 예약 승인 OR 거절 처리하는 기능을 구현하였습니다.
- 예약 관련 API들 Security 적용
=> feat: 그룹 관리자가 예약 내역을 선택하여 해당 예약 승인 OR 거절 처리하는 기능 구현

Backend/src/main/java/gwangju/ssafy/backend/domain/group/controller/GroupSignupController.java, Backend/src/main/java/gwangju/ssafy/backend/domain/group/exception/GroupError.java, Backend/src/main/java/gwangju/ssafy/backend/domain/group/repository/GroupSignupRepository.java, Backend/src/main/java/gwangju/ssafy/backend/domain/group/service/GroupSignupService.java, Backend/src/main/java/gwangju/ssafy/backend/domain/group/service/impl/GroupMemberServiceImpl.java, Backend/src/main/java/gwangju/ssafy/backend/domain/group/service/impl/GroupSignupServiceImpl.java
**개요**
- #149 
- 회원이 그룹 가입 신청하는 기능 구현
**타입**
**작업 사항**
- 회원이 그룹 가입  신청하는 기능을 구현하였습니다. 해당 그룹의 그룹 관리자가 가입 신청을 승인하면 그룹 가입이 완료됩니다.
- 해당 API들 Security 적용
=> feat: 회원이 그룹 가입 신청하는 기능 구현

Backend/src/main/java/gwangju/ssafy/backend/domain/group/exception/GroupError.java, Backend/src/main/java/gwangju/ssafy/backend/domain/group/repository/GroupSignupRepository.java, Backend/src/main/java/gwangju/ssafy/backend/domain/group/service/impl/GroupSignupServiceImpl.java
**개요**
- #149 
- 회원이 그룹 가입 신청하는 기능을 일부 수정 및 보완하였습니다. 
**타입**
**작업 사항**
- 회원이 그룹 가입  신청하는 기능에서 기존에는 uerId로만 판단하였는데 groupId도 이용해서 판단하도록 하였습니다.
=> fix: 회원이 그룹 가입 신청하는 기능 일부 수정 및 보완

SSoc-Client/src/modules/Card.js, SSoc-Client/src/screens/GroupDetailBottomTabs/Manage/EditGroupInfoModal.js, SSoc-Client/src/screens/GroupDetailScreen.js, SSoc-Client/src/util/FetchUtil.js
**개요**
- Reservaton 관련 비동기 통신작업 중간 완료
**타입**
** 작업 내용**
- GroupDetailScreen.js > EditGroupInfoModal.js
- 검색조회 조금 더 살펴볼 필요성 있음
- 이미지 업로드 관련으로 살펴볼 필요성 존재
=> feat: group 관련 비동기 처리 중간 완료

Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/controller/ProductController.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/controller/ReservationController.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/dto/CreateProductRequest.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/dto/ProductInfo.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/service/ProductService.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/service/impl/ProductServiceImpl.java
**개요**
- #149 
- 해당 그룹에서 그룹장이 대여 물품 생성하는 기능 구현
**타입**
**작업 사항**
- 해당 그룹의 그룹관리자가 대여 물품 생성하는 기능을 구현하였습니다.
=> feat: 대여 물품 생성 기능 구현

Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/controller/ProductController.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/repository/ProductRepository.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/repository/ReservationRepository.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/service/ProductService.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/service/impl/ProductServiceImpl.java
**개요**
- #157 
- 해당 그룹에서 그룹장이 대여 물품 삭제하는 기능 구현
**타입**
**작업 사항**
- 해당 그룹의 그룹관리자가 대여 물품을 삭제하는 기능을 구현하였습니다.
=> feat: 대여 물품 삭제 기능 구현

SSoc-Client/package.json, SSoc-Client/src/modules/ImgEditButton.js
**개요**
- fix: 프로필 이미지 업로드시 토큰 오류 해결 
**타입**
** 작업 내용**
=> fix: 프로필 이미지 업로드시 토큰 오류 해결

Backend/src/main/java/gwangju/ssafy/backend/domain/group/controller/GroupSignupController.java, Backend/src/main/java/gwangju/ssafy/backend/domain/group/service/GroupSignupService.java, Backend/src/main/java/gwangju/ssafy/backend/domain/group/service/impl/GroupSignupServiceImpl.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/controller/ReservationController.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/dto/GetReservationProduct.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/repository/ReservationRepository.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/service/ReservationService.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/service/impl/ReservationServiceImpl.java
**개요**
- #157 
- 그룹원 자기 자신이 예약한 대여 물품 내역 조회하는 기능 구현
**타입**
**작업 사항**
- 그룹원이 자기 자신이 예약한 대여 물품 내역을 조회하는 기능을 구현하였습니다.
=> feat: 그룹원인 내가 예약한 대여 물품 내역 조회하는 기능 구현

Backend/src/main/java/gwangju/ssafy/backend/domain/account/controller/GroupAccountController.java, Backend/src/main/java/gwangju/ssafy/backend/domain/account/dto/GetMyGroupAccountRequest.java, Backend/src/main/java/gwangju/ssafy/backend/domain/account/dto/GroupAccountInfo.java, Backend/src/main/java/gwangju/ssafy/backend/domain/account/repository/GroupAccountRepository.java, Backend/src/main/java/gwangju/ssafy/backend/domain/account/service/GroupAccountService.java, Backend/src/main/java/gwangju/ssafy/backend/domain/account/service/impl/GroupAccountServiceImpl.java
**개요**
-
- 가입 그룹 계좌 조회 API 구현
**타입**
**작업 사항**
-  가입 그룹 계좌 조회 API 구현
=> feat: 가입 그룹 계좌 조회 API 구현

Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/exception/ReservationError.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/exception/ReservationException.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/exception/ReservationHandler.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/service/impl/ProductServiceImpl.java, Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/service/impl/ReservationServiceImpl.java, Backend/src/main/java/gwangju/ssafy/backend/domain/user/controller/UserController.java, Backend/src/main/java/gwangju/ssafy/backend/global/component/jwt/repository/RefreshRepository.java, Backend/src/main/java/gwangju/ssafy/backend/global/config/TestConfig.java, Backend/src/main/java/gwangju/ssafy/backend/global/infra/email/service/impl/EmailServiceImpl.java
**개요**
- #172 
- Exception 핸들링이 안된 도메인 부분들을 추가 예외처리 작업 및 핸들링 작업 처리 작업
**타입**
**작업 사항**
- 예약 도메인(예약내역 및 대여물품 관련)에 Exception 핸들링 처리를 해줬습니다.
=> feat: Exception 핸들링 안된 도메인 부분들 처리

SSoc-Client/src/modules/Board/EditContent.js, SSoc-Client/src/modules/Settlement/LineGraph.js, SSoc-Client/src/screens/GroupDetailBottomTabs/Settlement/DailySettlementScreen.js, SSoc-Client/src/screens/GroupDetailBottomTabs/Settlement/MonthlySettlementSceen.js, SSoc-Client/src/screens/GroupDetailBottomTabs/Settlement/SettlementReportScreen.js, SSoc-Client/src/util/FetchUtil.js
**개요**
- feat: Settlement 비동기 처리 중간 커밋
**타입**
** 작업 내용**
=> feat: Settlement 비동기 처리 중간 커밋

Backend/src/main/java/gwangju/ssafy/backend/domain/reservation/service/impl/ReservationServiceImpl.java, Backend/src/main/java/gwangju/ssafy/backend/global/infra/email/service/impl/EmailServiceImpl.java
**개요**
- #165 
- 그룹 관리자가 물품 예약 승인 OR 거절 시 예약한 해당 인원에게 메일 발송하는 기능을 구현
**타입**
**작업 사항**
- 그룹 관리자가 물품 예약 승인 OR 거절 시 예약한 해당 인원에게 메일 발송하는 기능을 구현하였습니다..
=> feat: 그룹관리자가 물품 예약 승인 OR 거절 시 예약한 해당 인원에게 메일 발송 기능 구현

Backend/src/main/java/gwangju/ssafy/backend/domain/user/dto/UserSignUpRequestDto.java
**개요**
- fix: 회원가입시 userImageUrl 기본값 설정
**타입**
** 작업 내용**
fix: null값이 아닌 기본값이 들어가게끔 설정
=> fix: 이미지 null값 안들어가게끔 수정

SSoc-Client/src/modules/ImgEditButton.js, SSoc-Client/src/modules/Settlement/TransactionItem.js, SSoc-Client/src/screens/GroupDetailBottomTabs/Settlement/DailySettlementScreen.js, SSoc-Client/src/screens/GroupDetailBottomTabs/Settlement/MonthlySettlementSceen.js, SSoc-Client/src/screens/GroupDetailBottomTabs/Settlement/SettlementReportScreen.js, SSoc-Client/src/util/FetchUtil.js
**개요**
- #170 
- 정산 구현 
**타입**
**작업 사항**
- 정산 페이지 연동
=> feat: 정산 페이지 api 연동 
